### ISSUE TITLE
ACID for saveAll method

### ISSUE THREAD

**Issue by linux-code** [microsoft/spring-data-cosmosdb#527] opened 2020-04-07 07:14 UTC
Hi,

Is saveAll method ACID compliant if we pass list of documents with same logical partition-key value?

**Comment by kushagraThapar** [comment] 2020-04-07 16:24
No, saveAll is not ACID compliant.
Spring-data-cosmosdb doesn’t support bulk operations as of now, it only iterates over the list of documents passed to saveAll, and saves them one by one.
 
We are working on bulk operations for spring-data-cosmosdb. Will let you know once the functionality is present.

**Comment by kushagraThapar** [comment] 2020-07-01 17:19
Duplicate of : https://github.com/microsoft/spring-data-cosmosdb/issues/407

**Comment by kushagraThapar** [comment] 2020-07-01 17:33
Closing it here as this is being tracked in a separate repo.

**Closed by kushagraThapar** 2020-07-01 17:33 UTC
